export const projects = [
	{
		name: 'BDC Radio redesign',
		category: 'Featured project · Website & broadcast platform',
		url: 'https://bdcradio.com',
		linkLabel: 'Visit website',
		image: '/assets/images/projects/bdc-redesign.webp',
		description: 'A new home for local radio. The bdcradio.com redesign brings eight station profiles, six live streams, shows, sports scores, and community news together, with a player that keeps the music going as listeners explore.',
		features: ['Persistent radio player', 'Live scores & local news', 'Station & show directories'],
		accent: '#ece9df',
		featured: true,
		details: [
			{
				title: 'Behind the broadcast',
				text: 'A fast Astro website connects to a Django backend for station information, schedules, and sports scores. Staff manage the platform through a central admin, while AzuraCast and Icecast deliver the audio.',
			},
			{
				title: 'Keeping it current',
				text: 'Celery workers and Redis support background jobs that poll stream data every minute, recording listener counts and stream status. A metadata bridge brings in song and show information from broadcast equipment; the website refreshes scores every 30 seconds while visible.',
			},
			{
				title: 'A voice for the community',
				text: 'The shared backend also powers weekly audience polls for the News Now sites. Reusable WordPress embeds connect voting and results to centrally managed polls, with reporting tools for staff.',
			},
		],
	},
	{
		name: 'SatCom Meeting Notes',
		category: 'AI meeting assistant',
		url: 'https://satcom-meetingminutes.netlify.app',
		image: '/assets/images/projects/meeting-notes.png',
		imageAlt: 'Meeting Notes by SatCom — Good conversations. Clear minutes. Next steps.',
		description: 'Upload a recording for transcription or start with a pasted transcript, then generate draft minutes, decisions, and action items. This working demo lets you review and edit the results, track next steps, and download notes to share.',
		features: ['Audio transcription & draft minutes', 'Decisions & action-item tracking', 'Editable notes & Markdown downloads'],
		accent: '#dce9df',
	},
	{
		name: 'Sabine Community Connection',
		category: 'Community website',
		url: 'https://sabinecommunityconnection.com',
		image: '/assets/images/projects/community.webp',
		description: 'A welcoming online home for a Sabine Parish nonprofit, connecting families and volunteers with local programs and ways to get involved.',
		features: ['Program information', 'Community photo gallery', 'Volunteer & contact resources'],
		accent: '#e9f0df',
	},
	{
		name: 'SOLE to SOUL YOGA',
		category: 'Booking app',
		url: 'https://yoga.allthingssabine.com',
		image: '/assets/images/projects/yoga.webp',
		description: 'A simple path from finding a yoga class to saving a spot. Students can browse the schedule and see available spaces without creating an account.',
		features: ['Class schedule', 'Available spaces', 'Booking without an account'],
		accent: '#f6e6dd',
	},
	{
		name: 'BDC Radio',
		category: 'Streaming platform',
		url: 'https://radio.bdcradio.com',
		image: '/assets/images/projects/radio.webp',
		description: 'Local radio in one place, with live station streams, now-playing information, news updates, and community polls.',
		features: ['Live station streams', 'Now-playing information', 'News & community polls'],
		accent: '#e0eaf7',
	},
	{
		name: 'All Things Sabine Menus',
		category: 'Local dining app',
		url: 'https://menus.allthingssabine.com',
		image: '/assets/images/projects/menus.webp',
		description: 'A local menu drawer that makes choosing a place to eat easier. Browse restaurant menus, put together a shareable list, and help others discover nearby favorites.',
		features: ['Restaurant menus', 'Shareable lists', 'Community menu submissions'],
		accent: '#f1e4d4',
	},
	{
		name: 'Many Airspace',
		category: 'Live aircraft dashboard',
		url: 'https://many-airspace.netlify.app/',
		image: '/assets/images/projects/many-airspace.webp',
		description: 'A live look at the skies around Many, Louisiana. Explore an interactive aircraft map, see flight details, and follow notable aircraft using locally received radio data.',
		features: ['Live aircraft map', 'Aircraft details & watchlist', 'Receiver activity dashboard'],
		accent: '#dcebe7',
	},
	{
		name: 'Nourish Ledger',
		category: 'Nutrition diary app',
		url: 'https://nourish-ledger.netlify.app/',
		image: '/assets/images/projects/nourish-ledger.webp',
		description: 'A personal nutrition diary for logging meals, tracking nutrients, and keeping recipes and goals together. Food search, barcode scanning, and AI-assisted meal-photo drafts help make daily entries easier.',
		features: ['Meal & nutrient tracking', 'Food search & barcode scanning', 'AI-assisted meal-photo drafts'],
		accent: '#e7ebe1',
	},
];
